/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Log_In_Type;

import static Log_In_Type.Customer_New_account.customers_arrayList;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;

/**
 *
 * @author Aans
 */
public class Block_Customer extends javax.swing.JFrame {

    /**
     * Creates new form Block_Customer
     */
    public Block_Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Customer_to_be_Blocked = new javax.swing.JTextField();
        Block_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Which customer do you want to block: ");

        Customer_to_be_Blocked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_to_be_BlockedActionPerformed(evt);
            }
        });

        Block_Button.setText("Block");
        Block_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Block_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(Customer_to_be_Blocked, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(Block_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Customer_to_be_Blocked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(Block_Button)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String name;
    private void Customer_to_be_BlockedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_to_be_BlockedActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Customer_to_be_BlockedActionPerformed
String data[];
String password;
boolean Customer_Status;
//    void read ()
//     {
//         try {
//             FileReader fileReader = new FileReader("Customers_Data.csv");
//             BufferedReader bufferedReader = new BufferedReader(fileReader);
//             String line;
////             String name,password;
//             for (int i=0;(line = bufferedReader.readLine())!=null;i++)
//             {
//                  data = line.split(",");
//                  name = data[0];
//                  password = data[1];
//                  Customer_Status = Boolean.valueOf(data[2]);
//                  
//                 Customers customers = new Customers(name,password,Customer_Status);
//                 customers_arrayList.add(customers);
//             }
//             bufferedReader.close();
//             System.out.println("Readed");
//         }catch (Exception e)
//         {
//             System.out.println("ERROR");
//             e.printStackTrace();
//         }
//     }


    
    void replace(String customer_name,  boolean status)
    {
        try {
            FileInputStream fstream = new FileInputStream("Customer_Data.csv");
            BufferedReader br = new BufferedReader(new InputStreamReader(fstream));
            String strLine;
            StringBuilder fileContent = new StringBuilder();
            while ((strLine = br.readLine()) != null) {
                String tokens[] = strLine.split(",");
                if (customer_name.equalsIgnoreCase(tokens[0])) {
                    tokens[2] = String.valueOf(status);
                    String newLine = tokens[0] + "," + tokens[1]+","+tokens[2];
                    fileContent.append(newLine);
                    fileContent.append("\n");

                } else {
                    fileContent.append(strLine);
                    fileContent.append("\n");
                }
            }
            FileWriter fstreamWrite = new FileWriter("Customer_Data.csv");
            BufferedWriter out = new BufferedWriter(fstreamWrite);
            out.write(fileContent.toString());
            out.close();
            fstream.close();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }

    
    private void Block_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Block_ButtonActionPerformed
        // TODO add your handling code here:
//                read();

         name = Customer_to_be_Blocked.getText();
        System.out.println(name);
        System.out.println(customers_arrayList.size());
        boolean check = false;
//        Customer_Log_in customer_Log_in = new Customer_Log_in();
//        customer_Log_in.Customer_Status = true;
//        Customer_New_account customer_New_account = new Customer_New_account();
        for (int i= 0; i<customers_arrayList.size();i++ )
        {
            System.out.println(customers_arrayList.get(i).name);

            if (name.equalsIgnoreCase(customers_arrayList.get(i).name))
            {
                customers_arrayList.get(i).setStatus(true);
                JOptionPane.showMessageDialog(null, "Customer blocked!");
                check = true;
                replace(name, check);
            }    
        }
        if(check == false)
            JOptionPane.showMessageDialog(null, "Customer not blocked!");
dispose();
Rider_Menu rider_Menu = new Rider_Menu();
rider_Menu.setVisible(true);
    }//GEN-LAST:event_Block_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Block_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Block_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Block_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Block_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Block_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Block_Button;
    private javax.swing.JTextField Customer_to_be_Blocked;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
