/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Log_In_Type;

import static Log_In_Type.Resturant_new_Account.resturants_arrayList;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JFrame;



/**
 *
 * @author Aans
 */
public class Log_In_Type extends javax.swing.JFrame {

    /**
     * Creates new form Log_In_Type
     */
    public Log_In_Type() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Account_type_Label = new javax.swing.JLabel();
        customer_logIn_Button = new javax.swing.JButton();
        rider_logIn_Button = new javax.swing.JButton();
        admin_logIn_Button = new javax.swing.JButton();
        resturant_logIn_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In Type");

        Account_type_Label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Account_type_Label.setText("Which Type of Account do you want to Log In or Sign up?");

        customer_logIn_Button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customer_logIn_Button.setText("As a Customer");
        customer_logIn_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_logIn_ButtonActionPerformed(evt);
            }
        });

        rider_logIn_Button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rider_logIn_Button.setText("As a Rider");
        rider_logIn_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rider_logIn_ButtonActionPerformed(evt);
            }
        });

        admin_logIn_Button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        admin_logIn_Button.setText("As an Admin");
        admin_logIn_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_logIn_ButtonActionPerformed(evt);
            }
        });

        resturant_logIn_Button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resturant_logIn_Button.setText("As a Resturant");
        resturant_logIn_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resturant_logIn_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Account_type_Label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(resturant_logIn_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rider_logIn_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(admin_logIn_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customer_logIn_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Account_type_Label)
                .addGap(35, 35, 35)
                .addComponent(customer_logIn_Button)
                .addGap(18, 18, 18)
                .addComponent(resturant_logIn_Button)
                .addGap(18, 18, 18)
                .addComponent(rider_logIn_Button)
                .addGap(18, 18, 18)
                .addComponent(admin_logIn_Button)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }
    private void customer_logIn_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_logIn_ButtonActionPerformed
        // TODO add your handling code here:      
        Customer_Log_in customer_log_in = new Customer_Log_in();
//        customer_log_in.menu();
        customer_log_in.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_customer_logIn_ButtonActionPerformed

    private void rider_logIn_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rider_logIn_ButtonActionPerformed
        // TODO add your handling code here:
     
        Rider_Log_in rider_log_in = new Rider_Log_in();
//        rider_log_in.menu();
        rider_log_in.setVisible(true);
        dispose();
    }//GEN-LAST:event_rider_logIn_ButtonActionPerformed

    private void admin_logIn_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_logIn_ButtonActionPerformed
        // TODO add your handling code here:
      
        Admin_Log_in admin_log_in = new Admin_Log_in();
//        admin_log_in.menu();
        admin_log_in.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_logIn_ButtonActionPerformed

    private void resturant_logIn_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resturant_logIn_ButtonActionPerformed
        // TODO add your handling code here:
    
        Resturant_Log_In resturant_log_in = new Resturant_Log_In();
//        resturant_log_in.menu();
        resturant_log_in.setVisible(true);
        dispose();
    }//GEN-LAST:event_resturant_logIn_ButtonActionPerformed

    
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_In_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_In_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_In_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_In_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Resturant_Log_In resturant_Log_In = new Resturant_Log_In();
        resturant_Log_In.read();
        Customer_Log_in customer_Log_in = new Customer_Log_in();
        customer_Log_in.read();
        Rider_Log_in rider_Log_in = new Rider_Log_in();
        rider_Log_in.read();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_In_Type().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account_type_Label;
    private javax.swing.JButton admin_logIn_Button;
    private javax.swing.JButton customer_logIn_Button;
    private javax.swing.JButton resturant_logIn_Button;
    private javax.swing.JButton rider_logIn_Button;
    // End of variables declaration//GEN-END:variables
}
