/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Log_In_Type;
//import static Log_In_Type.Resturants_Foods.Cart_ArrayList;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aans
 */
public class Resturant_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Resturant_Menu
     */
    public Resturant_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Update_Food_Details_Button = new javax.swing.JButton();
        Update_Food_Delivery_Status_Button = new javax.swing.JButton();
        Add_Food_Details_Button = new javax.swing.JButton();
        Delete_Food_Button = new javax.swing.JButton();
        Check_Food_Order_Button = new javax.swing.JButton();
        Calculate_Bill_Button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Resturant Menu");

        Update_Food_Details_Button.setText("Update Food details");
        Update_Food_Details_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_Food_Details_ButtonActionPerformed(evt);
            }
        });

        Update_Food_Delivery_Status_Button.setText("Update food delivery status");
        Update_Food_Delivery_Status_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_Food_Delivery_Status_ButtonActionPerformed(evt);
            }
        });

        Add_Food_Details_Button.setText("Add Food details");
        Add_Food_Details_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Food_Details_ButtonActionPerformed(evt);
            }
        });

        Delete_Food_Button.setText("Delete Food");
        Delete_Food_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Food_ButtonActionPerformed(evt);
            }
        });

        Check_Food_Order_Button.setText("Check food order");
        Check_Food_Order_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_Food_Order_ButtonActionPerformed(evt);
            }
        });

        Calculate_Bill_Button.setText("Calculate Bills");
        Calculate_Bill_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculate_Bill_ButtonActionPerformed(evt);
            }
        });

        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Check_Food_Order_Button))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(back_button)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Update_Food_Delivery_Status_Button)
                                    .addComponent(Add_Food_Details_Button, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Delete_Food_Button, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Update_Food_Details_Button, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Calculate_Bill_Button, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_Food_Details_Button)
                    .addComponent(Update_Food_Details_Button))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete_Food_Button)
                    .addComponent(Check_Food_Order_Button))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update_Food_Delivery_Status_Button)
                    .addComponent(Calculate_Bill_Button))
                .addGap(18, 18, 18)
                .addComponent(back_button)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ArrayList <Foods> foods = new ArrayList<Foods>();
//    Resturant_Log_In resturant_Log_In = new Resturant_Log_In();
//        String name = resturant_Log_In.getName();
    private void Add_Food_Details_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Food_Details_ButtonActionPerformed
        // TODO add your handling code here:
        
//        Add_Food add_Food = new Add_Food();
//        add_Food.main();
        
        
        Add_Food add_Food = new Add_Food();
        add_Food.setVisible(true);
    }//GEN-LAST:event_Add_Food_Details_ButtonActionPerformed

    
   static ArrayList <Customer_Cart> Resturant_Order = new ArrayList<Customer_Cart>();
      
    String data[];
    String Food_name;
    double Food_price;
    void read ()
     {
         try {
             FileReader fileReader = new FileReader("Food_Cart.csv");
             BufferedReader bufferedReader = new BufferedReader(fileReader);
             String line;
//             String name,password;
             for (int i=0;(line = bufferedReader.readLine())!=null;i++)
             {
                  data = line.split(",");
                  Food_name = data[0];
                  Food_price = Double.valueOf(data[1]);
                 Customer_Cart customer_Cart = new Customer_Cart(Food_name,Food_price);
                 Resturant_Order.add(customer_Cart);
             }
             bufferedReader.close();
             System.out.println("Readed");
         }catch (Exception e)
         {
             System.out.println("ERROR");
             e.printStackTrace();
         }
     }

 
   
   
    
    private void Check_Food_Order_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_Food_Order_ButtonActionPerformed
        // TODO add your handling code here:
        System.out.println(Resturant_Order.size());
        if (Resturant_Order.size()>0)
        {
            JFrame Resturants_Order_Frame = new JFrame ("Resturants_Order");
            Resturants_Order_Frame.setLayout(new GridLayout(5,5));
//            Resturants_Order_Frame.setBounds(50,50,20,20);

        for (int i =0; i<Resturant_Order.size(); i++)
        {
            
            System.out.println(Resturant_Order.size());
            System.out.println("FOod name: "+Resturant_Order.get(i).Name);
            System.out.println("FOod Price: "+Resturant_Order.get(i).Price);
            System.out.println();
            
            JLabel Food_name = new JLabel (Resturant_Order.get(i).Name); 
            JLabel Food_price = new JLabel (String.valueOf(Resturant_Order.get(i).Price));
            
            JPanel panel = new JPanel();
            panel.setBackground(Color.LIGHT_GRAY);
            panel.add(Food_name);
            panel.add(Food_price);
            
            Resturants_Order_Frame.add(panel);
            Resturants_Order_Frame.setVisible(true);
            
        }
        }else
        {
            JOptionPane.showMessageDialog(null, "---!No Food Order!---");
        }
//        Resturants_Foods resturants_Foods = new Resturants_Foods();
    }//GEN-LAST:event_Check_Food_Order_ButtonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        Log_In_Type log_In_Type = new Log_In_Type();
        log_In_Type.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void Update_Food_Details_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_Food_Details_ButtonActionPerformed
        // TODO add your handling code here:
       Update_Food_Details update_Food_Details = new Update_Food_Details();
       dispose();
       update_Food_Details.setVisible(true);
    }//GEN-LAST:event_Update_Food_Details_ButtonActionPerformed

    private void Delete_Food_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Food_ButtonActionPerformed
        // TODO add your handling code here:
        Delete_Food1 delete_Food1 = new Delete_Food1();
        dispose();
        delete_Food1.setVisible(true);
        
    }//GEN-LAST:event_Delete_Food_ButtonActionPerformed

    private void Calculate_Bill_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculate_Bill_ButtonActionPerformed
        // TODO add your handling code here:
        double total_price = 0.0;
        System.out.println(Resturant_Order.size());
        for (int i=0; i<Resturant_Order.size(); i++)
        {
            total_price+=Resturant_Order.get(i).getPrice();
        }
        JOptionPane.showMessageDialog(null, "Total Bill of the Cart: "+total_price);
    }//GEN-LAST:event_Calculate_Bill_ButtonActionPerformed
    Resturants_Foods resturants_Foods = new Resturants_Foods();
    private void Update_Food_Delivery_Status_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_Food_Delivery_Status_ButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Order Ready to be Dilivered to Rider!");
        resturants_Foods.Food_Status.setText("Order Ready to be Dilivered to Rider!");
    }//GEN-LAST:event_Update_Food_Delivery_Status_ButtonActionPerformed

//    public void ActionListeners(String name)
//    {
//    Add_Food_Details_Button.addActionListener(new ActionListener() {
//        @Override
//        public void actionPerformed(ActionEvent e) {
//               Add_Food add_Food = new Add_Food(name);
//               add_Food.setVisible(true);
//        }
//    }
//    
//    );
//    
//    }
    
//    public void Resturant_Cart()
//    {
//        Resturants_Foods resturants_Foods = new Resturants_Foods();
//        System.out.println(resturants_Foods.Cart_ArrayList.size());
//        System.out.println(resturants_Foods.Cart_ArrayList.get(1));
//        
//        
//    }
    
    
    /**
     * @param args the command line arguments
     */
    public void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        Resturant_Cart();
//        ActionListeners(name);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resturant_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resturant_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resturant_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resturant_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        ActionListeners(String name);
        /* Create and display the form */
        read();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resturant_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Food_Details_Button;
    private javax.swing.JButton Calculate_Bill_Button;
    private javax.swing.JButton Check_Food_Order_Button;
    private javax.swing.JButton Delete_Food_Button;
    private javax.swing.JButton Update_Food_Delivery_Status_Button;
    private javax.swing.JButton Update_Food_Details_Button;
    private javax.swing.JButton back_button;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
